services:
  # 1. Oracle Database
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: erp-oracle
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=Spring_app
      - APP_PASSWORD=spring_password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Redis
  redis:
    image: redis:alpine
    container_name: erp-redis
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
      --activedefrag yes
      --active-defrag-ignore-bytes 50mb
      --active-defrag-threshold-lower 10
      --active-defrag-threshold-upper 30
      --hash-max-listpack-entries 512
      --hash-max-listpack-value 64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 3. MinIO
  minio:
    image: minio/minio
    container_name: erp-minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # 4. Kafka (KRaft mode with SASL_PLAINTEXT enabled)
  kafka:
    image: bitnami/kafka:3.8
    container_name: erp-kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9092,INTERNAL://:29092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # SASL Setup
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=kafka@2025
    volumes:
      - kafka_data:/bitnami/kafka
  # 5. Spring Boot App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - DB_USERNAME=Spring_app
      - DB_PASSWORD=spring_password
      - REDIS_HOST=redis
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin12345
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_USER=kafka
      - KAFKA_PASSWORD=kafka@2025
    depends_on:
      oracle:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_started

volumes:
  oracle_data:
  redis_data:
  minio_data:
  kafka_data:
